//
// AdvisorUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct AdvisorUser: Codable, Hashable {

    /** The customer&#39;s name */
    public var name: String
    /** The customer&#39;s last name */
    public var lastName: String
    /** The customer&#39;s cellphone number */
    public var cellphone: String
    /** Customer UUID assigned by Bamba */
    public var uuid: String?

    public init(name: String, lastName: String, cellphone: String, uuid: String? = nil) {
        self.name = name
        self.lastName = lastName
        self.cellphone = cellphone
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case lastName
        case cellphone
        case uuid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(cellphone, forKey: .cellphone)
        try container.encodeIfPresent(uuid, forKey: .uuid)
    }
}
