//
// AdvisorMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct AdvisorMessageRequest: Codable, Hashable {

    public var customer: AdvisorUser
    public var message: Message

    public init(customer: AdvisorUser, message: Message) {
        self.customer = customer
        self.message = message
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customer
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customer, forKey: .customer)
        try container.encode(message, forKey: .message)
    }



}
