//
// CancellationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct CancellationResponse: Codable, Hashable {

    public var id: UUID?
    /** Benefit */
    public var name: String?
    /** Plan benefit summary */
    public var brief: String?
    /** Cancellation status */
    public var state: String?
    /** The date and time (ISO 8601 format) of cancellation */
    public var canceledAt: Date?

    public init(id: UUID? = nil, name: String? = nil, brief: String? = nil, state: String? = nil, canceledAt: Date? = nil) {
        self.id = id
        self.name = name
        self.brief = brief
        self.state = state
        self.canceledAt = canceledAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case brief
        case state
        case canceledAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(brief, forKey: .brief)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(canceledAt, forKey: .canceledAt)
    }
}
