//
// Customer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Customer: Codable, Hashable {

    /** The customer&#39;s name */
    public var name: String
    /** The customer&#39;s last name */
    public var lastName: String
    /** The customer&#39;s second last name */
    public var secondLastName: String
    /** The customer&#39;s cellphone number */
    public var cellphone: String
    /** The customer&#39;s email */
    public var email: String
    /** The customer&#39;s birthdate on yyyy-mm-dd format */
    public var birthdate: Date
    /** The customer&#39;s gender, M for Male and F for Female */
    public var gender: String

    public init(name: String, lastName: String, secondLastName: String, cellphone: String, email: String, birthdate: Date, gender: String) {
        self.name = name
        self.lastName = lastName
        self.secondLastName = secondLastName
        self.cellphone = cellphone
        self.email = email
        self.birthdate = birthdate
        self.gender = gender
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case lastName
        case secondLastName
        case cellphone
        case email
        case birthdate
        case gender
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(secondLastName, forKey: .secondLastName)
        try container.encode(cellphone, forKey: .cellphone)
        try container.encode(email, forKey: .email)
        try container.encode(birthdate, forKey: .birthdate)
        try container.encode(gender, forKey: .gender)
    }
}
