//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct InlineResponse200: Codable, Hashable {

    /** The unique identifier for the order */
    public var id: Int?
    /** The state of the order */
    public var state: String?
    /** The unique identifier for the customer on Bamba®, you MUST relate this with user/customer on your platform */
    public var customerId: String?
    /** The date and time (ISO 8601 format) when the order was created */
    public var createdAt: Date?
    /** The date and time (ISO 8601 format) when the order was last modified. */
    public var updatedAt: Date?

    public init(id: Int? = nil, state: String? = nil, customerId: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.state = state
        self.customerId = customerId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case state
        case customerId
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(customerId, forKey: .customerId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }



}
