//
// InlineResponse422Errors.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct InlineResponse422Errors: Codable, Hashable {

    public var field: [String]?

    public init(field: [String]? = nil) {
        self.field = field
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case field
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(field, forKey: .field)
    }
}
