//
// Message.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Message: Codable, Hashable {

    /** The customer cellphone */
    public var from: String?
    /** The text of the message */
    public var text: String?
    /** The date and time (ISO 8601 format) when the message was sent */
    public var sentAt: Date?

    public init(from: String? = nil, text: String? = nil, sentAt: Date? = nil) {
        self.from = from
        self.text = text
        self.sentAt = sentAt
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case text
        case sentAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(sentAt, forKey: .sentAt)
    }



}
