//
// Message.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Message: Codable, Hashable {

    /** Message type */
    public var type: String
    /** The text of the message */
    public var message: String

    public init(type: String, message: String) {
        self.type = type
        self.message = message
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(message, forKey: .message)
    }



}
