//
// OrderProducts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct OrderProducts: Codable, Hashable {

    public var sku: String?

    public init(sku: String? = nil) {
        self.sku = sku
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sku
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sku, forKey: .sku)
    }



}
