//
// Order.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Order: Codable, Hashable {

    public var customer: Customer
    public var paymentParams: PaymentParams?
    /** The collection of SKU from the products selected by the customer */
    public var products: [OrderProducts]
    /** Its a unique identifier for the transaction/payment on your app */
    public var transactionId: String?

    public init(customer: Customer, paymentParams: PaymentParams? = nil, products: [OrderProducts], transactionId: String? = nil) {
        self.customer = customer
        self.paymentParams = paymentParams
        self.products = products
        self.transactionId = transactionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customer
        case paymentParams
        case products
        case transactionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customer, forKey: .customer)
        try container.encodeIfPresent(paymentParams, forKey: .paymentParams)
        try container.encode(products, forKey: .products)
        try container.encodeIfPresent(transactionId, forKey: .transactionId)
    }
}
