//
// Order.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Order: Codable, Hashable {

    public var customer: Customer
    /** The collection of SKU from the products selected by the customer */
    public var products: [OrderProducts]?

    public init(customer: Customer, products: [OrderProducts]? = nil) {
        self.customer = customer
        self.products = products
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customer
        case products
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customer, forKey: .customer)
        try container.encodeIfPresent(products, forKey: .products)
    }



}
