//
// PaymentParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct PaymentParams: Codable, Hashable {

    /** Media type key to make the payment, available options CREDIT_CARD, DEBIT_CARD, PHONE_NUMBER, EMAIL, CLABE, CACAO, CUSTOMER_NUMBER, ACCOUNT_NUMBER */
    public var mediaTypeKey: String
    /** The value for the selected media type, example if mediaTypeKey is EMAIL here it goes customer@domain.com */
    public var mediaTypeValue: String

    public init(mediaTypeKey: String, mediaTypeValue: String) {
        self.mediaTypeKey = mediaTypeKey
        self.mediaTypeValue = mediaTypeValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mediaTypeKey
        case mediaTypeValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mediaTypeKey, forKey: .mediaTypeKey)
        try container.encode(mediaTypeValue, forKey: .mediaTypeValue)
    }
}
