//
// ProductDescription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ProductDescription: Codable, Hashable {

    /** Section title */
    public var section: String?
    public var body: [String]?

    public init(section: String? = nil, body: [String]? = nil) {
        self.section = section
        self.body = body
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case section
        case body
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(section, forKey: .section)
        try container.encodeIfPresent(body, forKey: .body)
    }
}
