//
// ProductDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ProductDetails: Codable, Hashable {

    public var head: String?
    public var body: [String]?

    public init(head: String? = nil, body: [String]? = nil) {
        self.head = head
        self.body = body
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case head
        case body
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(head, forKey: .head)
        try container.encodeIfPresent(body, forKey: .body)
    }
}
