//
// ProductBundleItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ProductBundleItems: Codable, Hashable {

    /** The description of bundle content */
    public var description: String?

    public init(description: String? = nil) {
        self.description = description
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
    }



}
