//
// Service.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct Service: Codable, Hashable {

    /** The policy number of the customer service, some services does not have it */
    public var policyNumber: String?
    /** The description of the service */
    public var description: String

    public init(policyNumber: String? = nil, description: String) {
        self.policyNumber = policyNumber
        self.description = description
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case policyNumber
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(policyNumber, forKey: .policyNumber)
        try container.encode(description, forKey: .description)
    }



}
