name: BambaSDK
targets:
  BambaSDK:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [BambaSDK]
    info:
      path: ./Info.plist
      version: 1.0.4
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
    - carthage: AnyCodable
