//
// CustomerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CustomerAPI {
    /**
     Get customer services
     
     - parameter customerId: (path) Bamba customer unique identifier 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customerCustomerIdServicesGet(customerId: Int, apiResponseQueue: DispatchQueue = BambaSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Subscription?, _ error: Error?) -> Void)) {
        customerCustomerIdServicesGetWithRequestBuilder(customerId: customerId).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get customer services
     - GET /customer/{customerId}/services
     - Get all customer services
     - API Key:
       - type: apiKey x-api-key 
       - name: ApiKeyAuth
     - parameter customerId: (path) Bamba customer unique identifier 
     - returns: RequestBuilder<Subscription> 
     */
    open class func customerCustomerIdServicesGetWithRequestBuilder(customerId: Int) -> RequestBuilder<Subscription> {
        var path = "/customer/{customerId}/services"
        let customerIdPreEscape = "\(APIHelper.mapValueToPathItem(customerId))"
        let customerIdPostEscape = customerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{customerId}", with: customerIdPostEscape, options: .literal, range: nil)
        let URLString = BambaSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Subscription>.Type = BambaSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

    /**
     Cancel customer services
     
     - parameter customerId: (path) Bamba customer unique identifier 
     - parameter sku: (path) Service sku 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customerCustomerIdServicesSkuCancelGet(customerId: String, sku: String, apiResponseQueue: DispatchQueue = BambaSDKAPI.apiResponseQueue, completion: @escaping ((_ data: Subscription?, _ error: Error?) -> Void)) {
        customerCustomerIdServicesSkuCancelGetWithRequestBuilder(customerId: customerId, sku: sku).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Cancel customer services
     - GET /customer/{customerId}/services/{sku}/cancel
     - Cancel customer services
     - API Key:
       - type: apiKey x-api-key 
       - name: ApiKeyAuth
     - parameter customerId: (path) Bamba customer unique identifier 
     - parameter sku: (path) Service sku 
     - returns: RequestBuilder<Subscription> 
     */
    open class func customerCustomerIdServicesSkuCancelGetWithRequestBuilder(customerId: String, sku: String) -> RequestBuilder<Subscription> {
        var path = "/customer/{customerId}/services/{sku}/cancel"
        let customerIdPreEscape = "\(APIHelper.mapValueToPathItem(customerId))"
        let customerIdPostEscape = customerIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{customerId}", with: customerIdPostEscape, options: .literal, range: nil)
        let skuPreEscape = "\(APIHelper.mapValueToPathItem(sku))"
        let skuPostEscape = skuPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{sku}", with: skuPostEscape, options: .literal, range: nil)
        let URLString = BambaSDKAPI.basePath + path
        let parameters: [String: Any]? = nil

        let urlComponents = URLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            :
        ]

        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Subscription>.Type = BambaSDKAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (urlComponents?.string ?? URLString), parameters: parameters, headers: headerParameters)
    }

}
